name: soft_converter
description: Convert some videos and images to some formats
version: 0.3.0-dev
homepage: https://softyes.com.br
repository: https://github.com/softyesti/soft_converter

platforms:
  windows:
  macos:
  linux:

topics:
  - converter
  - image
  - video
  - ffmpeg
  - cwebp

environment:
  sdk: ^3.3.4

dependencies:
  path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  very_good_analysis: ^5.1.0
